### ISSUE TITLE
Add Kubectl command executor.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/container-debug-support#11]
Should work similarly to (and share a lot of code with) `Skaffold` in #7.

`Kubectl` should run `kubectl` commands, including but not limited to:
- `kubectl run --dry-run -o yaml`
- `kubectl logs`
- `kubectl port-forward`

**Comment by TadCordle** [comment]
Should we add a `KubectlDownloader` as well? Or are we assuming people already have it installed?

**Comment by coollog** [comment]
@TadCordle We'll assume (and check) that people have it installed. It could come from a variety of places including downloading the binary releases, building from source, installing via `gcloud`, etc.

**Comment by TadCordle** [comment]
A couple other questions: What are the intended use cases for this class? Should it be more generalized and low-level (i.e. you just pass in the `kubectl` flags and options as strings) or should there be specific method calls for each of our use cases (e.g. one for generating the k8s yaml, one of getting logs, etc.)?

**Comment by coollog** [comment]
@TadCordle 

Use cases:
- Generating kubernetes yaml #18 (`kubectl run...`/`kubectl expose ...`)
- Port-forwarding (`kubectl port-forward ...`)
- Getting logs (`kubectl logs ...`)
- And others that can easily be added

This class should be more low-level and provide just a wrapper for `kubectl` including subcommands and flags. The higher-level actions like generating YAML will be the responsibility of other classes.
