### ISSUE TITLE
Add actions to run "skaffold deploy".

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/container-debug-support#14]
- [ ] `skaffold-maven-plugin` - `skaffold:deploy`
- [ ] `skaffold-gradle-plugin` - `skaffoldDeploy`

These actions should (roughly):

- Check if `skaffold.yaml` exists.
  - If no:
    - Generate a `skaffold.yaml`
    - Grab target image reference from Jib
    - Generate kubernetes YAMLs (with `kubectl run`)
- Run `skaffold deploy`

**Comment by dkirrane** [comment]
Watching this plugin with interest.
I'd love to see a skaffold integration using Helm for packaging/deploying chart and Jib for Image build/push

Any thoughts on this plugin supporting Helm?

**Comment by loosebazooka** [comment]
Hi @dkirrane we're working on skaffold integration within skaffold and have currently deprioritized this as we work on that functionality. We will revisit this in the future.
