### ISSUE TITLE
Go Ductape Image for Alpine

### ISSUE THREAD

**Issue by panitaxx** [GoogleContainerTools/container-debug-support#30]
**Description of the issue**:

When using a binary created in an alpine image the delve cannot be used with the delve duct tape. It causes:

`standard_init_linux.go:211: exec user process caused "no such file or directory"`

**Expected behavior**:

Should run normally

**Steps to reproduce**: 

- Build a go program image from alpine linux container
-  Add duct-tape as an init container
- run skaffold with: 
`command: ["/dbg/go/bin/dlv","exec" ,"<executable>","--headless","--listen=:56268","--log"]` 

**Environment**: Ubuntu 19.10

**Comment by briandealwis** [comment]
Can you think of a way to determine whether an image is GLIBC or MUSL based?  To support distroless-style images, we need to avoid shell scripts.
