### ISSUE TITLE
Support for Java containers

### ISSUE THREAD

**Issue by yashbhutwala** [GoogleContainerTools/container-debug-support#32]
**Description of the issue**:

**Expected behavior**:

**Steps to reproduce**: 

**Environment**: 

**`skaffold-maven-plugin` Configuration:**
```xml
PASTE YOUR pom.xml CONFIGURATION HERE
```

--- OR ---

**`skaffold-gradle-plugin` Configuration:**
```xml
PASTE YOUR build.gradle CONFIGURATION HERE
```

**Log output**: 

**Additional Information**:

**Comment by loosebazooka** [comment]
Please add more information and reopen if you wish for us to address this.
