### ISSUE TITLE
`node` wrapper should have a list of acceptable entrypoints from node_modules

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/container-debug-support#45]
Next.JS apps seem to run via a binary in node_modules.  For example, [`next start -p 8080`](https://github.com/vincentjocodes/nextjs-test-app-cloud-code/blob/master/package.json), which is resolved to `node ./node_modules/.bin/next dev -p 8080`.

Currently the nodejs/wrapper blocks all applications from node_modules, but perhaps it should instead maintain a configurable block-list with `nodemon`.

**Comment by briandealwis** [comment]
@vincentjocodes do you know other `next`-like launcher binaries that should be included?

**Comment by vvvjo** [comment]
@briandealwis Hi Brian, I do not know of any other `next`-like binaries at this moment.
