### ISSUE TITLE
Helper images must support linux/arm64 for Apple M1

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/container-debug-support#60]
Docker on macOS for ARM builds images for the native architecture (`linux/arm64`), and `skaffold debug` will seem to break.

**Comment by j-windsor** [comment]
@briandealwis I believe this if fixed, right?

**Comment by briandealwis** [comment]
Thanks for the prod @j-windsor — this was fixed by https://github.com/GoogleContainerTools/container-debug-support/pull/64
