### ISSUE TITLE
python debug helper should not exit on undebuggable situations

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/container-debug-support#81]
`skaffold debug` fails on the [_Bank of Anthos_](https://github.com/GoogleCloudPlatform/bank-of-anthos) as the python launcher sees the `uwsgi`:
```
[contacts-65fc7dc6bf-tndvr contacts] time="2021-06-02T05:23:00Z" level=fatal msg="error launching python debugging: unable to determine python version from \"uwsgi\": exit status 1"
```

And it fails in a similar fashion on [`HipsterShop`](https://github.com/GoogleCloudPlatform/microservices-demo):
```
 > [loadgenerator-cdfcccf64-zlw22 main] time="2021-06-02T05:28:03Z" level=fatal msg="error launching python debugging: unable to determine python version from \"/bin/bash\": exit status 2"
```

The python launcher should not be erroring out in this situation but should just execute the original command line.

**Comment by j-windsor** [comment]
Is the problem here that since we are using an entrypoint that does not start with `python`, we don't know how to rewrite the entrypoint?

**Comment by briandealwis** [comment]
The `launch()` function already  executes the unadulterated command line if it has been disabled with an environment variable or if it determines the command line is already configured for debugging:
https://github.com/GoogleContainerTools/container-debug-support/blob/84e9fcdc1f4f574229aa503262639d7dfd370714/python/helper-image/launcher/launcher.go#L146-L156

But on encountering an error trying to determine how to launch a presumed python app, it just returns an error:
https://github.com/GoogleContainerTools/container-debug-support/blob/84e9fcdc1f4f574229aa503262639d7dfd370714/python/helper-image/launcher/launcher.go#L158-L171

which causes the `main()` to exit with an error message:
https://github.com/GoogleContainerTools/container-debug-support/blob/84e9fcdc1f4f574229aa503262639d7dfd370714/python/helper-image/launcher/launcher.go#L131-L133

What should happen instead is that the `launch()` should return an error when disabled or when already configured, and the error-handling code in `main()` should just run the unadulterated command line.

Feel up to putting together a patch?
